# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ontabilidadwebapp-frontend-linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Create deployment package
        run: |
          # Crear directorio para el paquete
          mkdir deployment_package
          
          # Copiar archivos necesarios para producción
          cp -r dist deployment_package/
          cp -r node_modules deployment_package/
          cp package.json deployment_package/
          cp server.js deployment_package/
          cp vite.config.ts deployment_package/ || true
          
          # Crear ZIP
          cd deployment_package
          zip -r ../app.zip . -x "*.git*" "*.md"
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-package
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2CEEF2D989F449EB5947FFE2AFFF6AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D331741FD651427090C6367C150087CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D2C012FD04584DE59F9BFCE0379F31F2 }}

      # NOTA: Las App Settings deben configurarse manualmente en Azure Portal:
      # WEBSITE_RUN_FROM_PACKAGE=1
      # SCM_DO_BUILD_DURING_DEPLOYMENT=false
      # NODE_ENV=production
      
      - name: Wait before deployment to avoid SCM conflicts
        run: sleep 15

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ontabilidadwebapp-frontend-linux'
          slot-name: 'Production'
          package: app.zip
          